spring:
  #mybatis配置
  datasource:
    username: root
    password: ENC(WXWaBiEdhad+aqD/luB+Kw==)
    url: jdbc:mysql:///onlineidea?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  druid:
    #2.连接池配置
    #初始化连接池的连接数量 大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    #配置获取连接等待超时的时间
    max-wait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 30000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
    #      pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20


#dubbo配置
dubbo:
  application:
    name: dubbo_service
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  protocol:
    name: dubbo
    port: 20880
  consumer:
    retries: 0
    timeout: 10000
  #扫描包的位置
  scan:
    base-packages: com.lzq.dubboservice.service