spring:
  profiles:
    active: dev
  application:
    #项目名称
    name: service
  #邮箱配置
  mail:
    host: smtp.163.com
    username: #用户账号
    password: #用户密码
    port: 465
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true



server:
  #服务器接口
  port: 8089


#数据加密
jasypt:
  encryptor:
    # 密钥
    password: WXRANDLZQ1998
    # 指定加密方式
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*xml
