resources:
  route: F:/项目/MyDemo/data/
  InitHtml: F:/项目/MyDemo/data/HelloWord.html

qiniuyun:
  accessKey: fIf9nYz-wQo3HD1AlhQ5wrUrdjtygUPGe2dpuLlY
  secretKey: ItVUX8sAaxsuj7kgmk3IZ0ip3BHljAx61N8m922C
  bucket: lzqwxr

chorme:
  value: F:/ChormeDriver/chromedriver.exe


spring:
  #静态资源访问
  resources:
      static-locations: file:${resources.route}
