resources:
  route: /home/demo/data/

qiniuyun:
  accessKey: Z_7eMJdtj_n4lrAdSs3zVuZ8rn4wZXu75b1gYJbC
  secretKey: QIriVPlgNKoKdjU02q166-7IBPy3z9sQTMn5Ae7R
  bucket: js-encoder

chorme:
  value: /usr/bin/chromedriver


spring:
  #静态资源访问
  resources:
      static-locations: file:${resources.route}
  #mybatis配置
  datasource:
    username: root
    password: ENC(WXWaBiEdhad+aqD/luB+Kw==)
    url: jdbc:mysql:///onlineidea?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
