spring:
  profiles:
    active: dev
  application:
    #项目名称
    name: web
  #rdis配置
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    password:
  #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: user
    password: wxr19980304

dubbo:
  application:
    name: dubbo_web
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  consumer:
    retries: 0
    timeout: 10000

#数据加密
jasypt:
  encryptor:
    # 密钥
    password: WXRANDLZQ1998
    # 指定加密方式
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

server:
  #服务器接口
  port: 8090
  tomcat:
    max-http-form-post-size: -1
  servlet:
    session:
      setMaxInactiveInterval: 60*60

logging:
  config: classpath:logback.xml