spring:
  profiles:
    active: dev
  application:
    #项目名称
    name: service
  #邮箱配置
  mail:
    host: smtp.163.com
    username: jsencoder@163.com
    password: IQQXAETMLUUSLACI
    port: 465
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true



#dubbo配置
dubbo:
  application:
    name: dubbo_service
  registry:
    protocol: zookeeper
    address: zookeeper://49.235.126.19:2181
    timeout: 600000
  protocol:
    name: dubbo
    port: 20880
  consumer:
    retries: 0
    timeout: 600000
  #扫描包的位置
  scan:
    base-packages: com.lzq.dubboservice.service
server:
  #服务器接口
  port: 8089


#数据加密
jasypt:
  encryptor:
    # 密钥
    password: WXRANDLZQ1998
    # 指定加密方式
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*xml
